config/routes.rb
MotoWebEngine::Engine.routes.draw do

  resources :runs
  resources :tests

  scope '/api' do
    resources :runs, controller: :api_runs, defaults: {format: :json}
    resources :tests, controller: :api_tests, defaults: {format: :json}
  end  

end

app/models/moto_web_engine/run.rb
module MotoWebEngine
  class Run < ActiveRecord::Base
    
    has_many :tests, dependent: :destroy
  
    enum result: { 
      pending: -2,
      running: -1,
      passed: 0,
      failure: 1,
      error: 2,
      skipped: 3
    }
    
  end
end

app/models/moto_web_engine/test.rb
module MotoWebEngine
  class Test < ActiveRecord::Base
    
    belongs_to :run
    
    enum result: { 
      pending: -2,
      running: -1,
      passed: 0,
      failure: 1,
      error: 2,
      skipped: 3
    }
  
  end
end

app/controllers/moto_web_engine/api_runs_controller.rb
require_dependency "moto_web_engine/application_controller"

module MotoWebEngine
  class ApiRunsController < ApplicationController

    # skip_before_action :verify_authenticity_token
    
    def index
      offset = params[:offset] || 0
      limit = params[:limit] || 20
      @runs = Run.order('id DESC').offset(offset).limit(limit)
      render json: @runs
    end

    def create
      input = JSON.parse(request.body.read)
      # validate input hash here (or delegate to some private method)
      run = Run.new input
      run.save!
      render json: run
    end

    def update
      run = Run.find params[:id]
      input = JSON.parse(request.body.read)
      # validate input hash here (or delegate to some private method)
      run.update input
      render json: run
    end

    def show
      run = Run.find params[:id]
      render json: run
    end

  end
end

app/controllers/moto_web_engine/api_tests_controller.rb
require_dependency "moto_web_engine/application_controller"

module MotoWebEngine
  class ApiTestsController < ApplicationController

    # skip_before_action :verify_authenticity_token
    
    def index
      offset = params[:offset] || 0
      limit = params[:limit] || 20
      @tests = Test.order('id DESC').offset(offset).limit(limit)
      render json: @tests
    end

    def create
      input = JSON.parse(request.body.read)
      # validate input hash here (or delegate to some private method)
      test = Test.new input
      test.save!
      render json: test
    end

    def update
      test = Test.find params[:id]
      input = JSON.parse(request.body.read)
      # validate input hash here (or delegate to some private method)
      test.update input
      render json: test
    end

    def show
      test = Test.find params[:id]
      render json: test
    end

  end
end

app/controllers/moto_web_engine/application_controller.rb
module MotoWebEngine
  class ApplicationController < ActionController::Base
  end
end

app/controllers/moto_web_engine/runs_controller.rb
require_dependency "moto_web_engine/application_controller"

module MotoWebEngine
  class RunsController < ApplicationController
    
    def index
      @runs = Run.order('created_at DESC').page(params[:page]).per(20)
    end    
    
    def show
      @run = Run.find(params[:id])
    end
    
  end
end

app/controllers/moto_web_engine/tests_controller.rb
require_dependency "moto_web_engine/application_controller"

module MotoWebEngine
  class TestsController < ApplicationController
    
    def show
      @test = Test.find params[:id]
      render layout: 'moto_web_engine/no_menu'
    end

  end
end

app/helpers/moto_web_engine/api_runs_helper.rb
module MotoWebEngine
  module ApiRunsHelper
  end
end

app/helpers/moto_web_engine/api_tests_helper.rb
module MotoWebEngine
  module ApiTestsHelper
  end
end

app/helpers/moto_web_engine/application_helper.rb
module MotoWebEngine
  module ApplicationHelper
    
    def bgcolor_result(result)
      case result.to_sym
      when :pending
        '#ffeeee'
      when :running
        '#ffcc00'
      when :passed
        '#00ff00'
      when :failure
        '#ff0000'
      when :error
        '#cc0099'
      when :skipped
        '#0066ff'
      else
        '#ffffff'
      end     
    end
    
    def duration(d)
      return '-' if d.nil?
      secs = d.to_i % 60
      mins = d.to_i / 60
      fraction = (d - d.to_i).round(3).to_s[2..-1]
      return "0.#{fraction}\"" if mins == 0 && secs == 0
      return "#{secs}.#{fraction}\"" if mins == 0
      "#{mins}'#{secs}.#{fraction}\""
    end
          
  end
end

app/helpers/moto_web_engine/runs_helper.rb
module MotoWebEngine
  module RunsHelper
  end
end

app/helpers/moto_web_engine/tests_helper.rb
module MotoWebEngine
  module TestsHelper
  end
end

app/views/layouts/moto_web_engine/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moto::TestResults</title>
  <%= stylesheet_link_tag    "moto_web_engine/application", media: "all" %>
  <%= javascript_include_tag "moto_web_engine/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'top_menu' %>
<hr />
<%= yield %>

</body>
</html>

app/views/layouts/moto_web_engine/no_menu.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moto::TestResults</title>
  <%= stylesheet_link_tag    "moto_web_engine/application", media: "all" %>
  <%= javascript_include_tag "moto_web_engine/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/moto_web_engine/application/_stats_bar.html.erb
<% 

return if run.result.to_sym.eql? :running

passed_percent = run.cnt_passed.to_f * 100 / run.cnt_all
failure_percent = run.cnt_failure.to_f * 100 / run.cnt_all
error_percent = run.cnt_error.to_f * 100 / run.cnt_all
skipped_percent = run.cnt_skipped.to_f * 100 / run.cnt_all

tooltip = "Total: #{run.cnt_all}\n"
tooltip << "Passed: #{run.cnt_passed} (#{passed_percent.round(2)}%)\n"
tooltip << "Failure: #{run.cnt_failure} (#{failure_percent.round(2)}%)\n"
tooltip << "Error: #{run.cnt_error} (#{error_percent.round(2)}%)\n"
tooltip << "Skipped: #{run.cnt_skipped} (#{skipped_percent.round(2)}%)"

%>

<div title="<%= tooltip %>">
<div style="float: left; display: inline-block; height: 14px; width: <%= passed_percent.round %>px; background-color: <%= bgcolor_result(:passed) %>;"></div>
<div style="float: left; display: inline-block; height: 14px; width: <%= failure_percent.round %>px; background-color: <%= bgcolor_result(:failure) %>;"></div>
<div style="float: left; display: inline-block; height: 14px; width: <%= error_percent.round %>px; background-color: <%= bgcolor_result(:error) %>;"></div>
<div style="float: left; display: inline-block; height: 14px; width: <%= skipped_percent.round %>px; background-color: <%= bgcolor_result(:skipped) %>;"></div>
</div>

app/views/moto_web_engine/application/_top_menu.html.erb
<%= link_to 'Results', runs_path %>

app/views/moto_web_engine/runs/index.html.erb
<table class="results">
	<thead>
		<th>Name</th>
		<th>Result</th>
		<th>User</th>
		<th>Host</th>
		<th>Started at</th>
		<th>Duration</th>
		<th>Stats</th>
	</thead>
	<tbody>		
<%
  i = 0 
  @runs.each do |r| 
    i += 1
%>
	<tr class="<%= i.odd? ? 'odd' : 'even' %>">
		<td><%= link_to r.name, r %></td>
		<td style="background-color: <%= bgcolor_result(r.result) %>"><%= r.result.upcase %></td>
		<td><%= r.user %></td>
		<td><%= r.host %></td>
		<td><%= r.created_at %></td>
		<td><%= duration r.duration %></td>
		<td style="padding: 0px;"><%= render partial: 'stats_bar', locals: { run: r } %></td>
	</tr>
<% end %>
	</tbody>
</table>
<br />
<%= paginate @runs %>

app/views/moto_web_engine/runs/show.html.erb
<%

if @run.result.to_sym.eql? :running
  passed_percent = ''
  failure_percent = ''
  error_percent = ''
  skipped_percent = ''
else
  passed_percent = "(#{(@run.cnt_passed.to_f * 100 / @run.cnt_all).round(2)}%)"
  failure_percent = "(#{(@run.cnt_failure.to_f * 100 / @run.cnt_all).round(2)}%)"
  error_percent = "(#{(@run.cnt_error.to_f * 100 / @run.cnt_all).round(2)}%)"
  skipped_percent = "(#{(@run.cnt_skipped.to_f * 100 / @run.cnt_all).round(2)}%)"
end
%>

<div class="test_header"><%= @run.name %></div>
<br />
<table class="top_summary">
	<tr>
		<th>Result:</th>
		<td style="background-color: <%= bgcolor_result(@run.result) %>"><%= @run.result.upcase %></td>
	</tr>
	<tr>
		<th>Started at:</th>
		<td><%= @run.created_at %></td>
	</tr>
	<tr>
		<th>User:</th>
		<td><%= @run.user %></td>
	</tr>
	<tr>
		<th>Host:</th>
		<td><%= @run.host %></td>
	</tr>
	<tr>
		<th>Duration:</th>
		<td><%= duration @run.duration %></td>
	</tr>
	<tr>
		<th># all</th>
		<td><%= @run.cnt_all %></td>
	</tr>
	<tr>
		<th># passed</th>
		<td><%= @run.cnt_passed %> <%= passed_percent %></td>
	</tr>
	<tr>
		<th># failure</th>
		<td><%= @run.cnt_failure %> <%= failure_percent %></td>
	</tr>
	<tr>
		<th># error</th>
		<td><%= @run.cnt_error %> <%= error_percent %></td>
	</tr>
	<tr>
		<th># skipped</th>
		<td><%= @run.cnt_skipped %> <%= skipped_percent %></td>
	</tr>
</table>

<br />

<table class="results">
	<thead>
		<th>Test name</th>
		<th>Result</th>
		<th>Duration</th>
	</thead>
	<tbody>		
<%
  i = 0 
  @run.tests.each do |t| 
    i += 1
%>
	<tr class="<%= i.odd? ? 'odd' : 'even' %>">
		<td><%= link_to(t.name, t, onclick: "javascript:(function(ele) { window.open(ele.href, ele.title,'toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=850,height=600,top=50,left=50')})(this); return false;") %></td>
		<td style="background-color: <%= bgcolor_result(t.result) %>"><%= t.result.upcase %></td>
		<td><%= duration t.duration %></td>
	</tr>
<% end %>
	</tbody>
</table>